export const COPY = {
  appName: 'Táxi Rio',
  loginTitle: 'Entrar',
  loginSubtitle: 'Escolha como deseja continuar',
  loginPassenger: 'Login como passageiro',
  loginDriver: 'Login como motorista',
  loggingIn: 'Entrando...',
  logout: 'Logout',
  logoutConfirmTitle: 'Sair da conta',
  logoutConfirmMessage: 'Deseja encerrar a sessão?',
  origin: 'Origem',
  destination: 'Destino',
  defaultOrigin: 'Copacabana, Rio de Janeiro',
  requestRide: 'Solicitar',
  requesting: 'Solicitando...',
  accepted: 'Corrida aceita! Em direção até o seu destino...',
  arrived: 'Você chegou ao seu destino!',
  closeFeedback: 'Fechar',
  requestConfirmTitle: 'Solicitar corrida',
  requestConfirmMessage: 'Confirma a solicitação desta corrida?',
  waiting: 'Aguardando corrida...',
  found: 'Corrida encontrada!',
  driving: 'Levando o passageiro até o seu destino...',
  acceptRide: 'Aceitar corrida',
  declineRide: 'Recusar corrida',
  finishRide: 'Finalizar corrida',
  acceptConfirmTitle: 'Aceitar corrida',
  acceptConfirmMessage: 'Deseja aceitar esta corrida?',
  declineConfirmTitle: 'Recusar corrida',
  declineConfirmMessage: 'Deseja recusar esta corrida e voltar a aguardar?',
  finishConfirmTitle: 'Finalizar corrida',
  finishConfirmMessage: 'Confirma que o passageiro chegou ao destino?',
  confirm: 'Confirmar',
  cancel: 'Cancelar',
  passenger: 'Passageiro',
  driver: 'Motorista',
  loginError: 'Não foi possível entrar. Tente novamente.',
  rideError: 'Não foi possível concluir a operação. Tente novamente.',
} as const
