server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /auth {
        proxy_pass http://taxi-rio-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_request_headers on;
    }

    location /corridas {
        proxy_pass http://taxi-rio-api:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_request_headers on;
    }

    location = /favicon.ico {
        try_files /taxi-rio.png =404;
        default_type image/png;
    }

    location ~* \.(?:js|css|png|svg|ico|woff2?|ttf|map)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
